### ISSUE TITLE
Unable to show existing files with nview command

### ISSUE THREAD

**Issue by WinDroid00** [vitorgalvao/note-taker-workflow#1]
### Workflow version

v2024.2

### Alfred version

5.5 (2257)

### macOS version

Sonoma 14.4

### Debugger output

```alfred_debugger
[23:04:10.314] Logging Started...
[23:04:20.847] Note Taker[Keyword] Processing complete
[23:04:20.854] Note Taker[Keyword] Passing output '' to JSON Config
[23:04:20.855] Note Taker[JSON Config] Processing complete
[23:04:20.857] Note Taker[JSON Config] Passing output '' to File Filter
```

### More details

After initial response from nview, file searching inside is not working. Not even with *
I have the below files (file creation is succesful ). Only sin I have done by keeping the folder inside gdrive (always available offline). Thank you
![CleanShot 2024-03-26 at 23 12 15](https://github.com/vitorgalvao/note-taker-workflow/assets/165063687/9504391f-2bc7-4a43-b088-7505e7b81756)

**Comment by vitorgalvao** [comment]
Use the [bult-in troubleshooting](https://www.alfredapp.com/help/troubleshooting/indexing/) on one of those file and post the output here.

**Comment by WinDroid00** [comment]
Starting Diagnostics...

File: 'Test notes.md'
Path: '/Users/zz/Library/CloudStorage/GoogleDrive-xxxxxxxxx@xxxxxx/My Drive/Alfred app/Alfred notes'

-----------------------------------------------------------

Check file cache database...

✅ File cache integrity is ok

-----------------------------------------------------------

Check if file is readable...

✅ Alfred has permissions to read this file.

Unix Permissions: 420
Underlying Type: NSFileTypeRegular
Extended Attributes: (
    "com.apple.lastuseddate#PS",
    "com.apple.quarantine",
    "com.apple.TextEncoding"
)

-----------------------------------------------------------

Check if volume '/' is indexed by macOS...

✅ Indexing is enabled on this drive

-----------------------------------------------------------

Check direct file metadata...

⚠️ Direct metadata available, but content type may be incorrect

Display Name: Test notes.md
 Other Names: 
Content Type: dyn.ah62d4rv4ge8043a
   Last Used: 2024-03-26 16:28:30 +0000

-----------------------------------------------------------

Check mdls file metadata...

✅ Metadata contains required items

_kMDItemDisplayNameWithExtensions  = "Test notes.md"
kMDItemContentCreationDate         = 2024-03-26 16:25:51 +0000
kMDItemContentCreationDate_Ranking = 2024-03-26 00:00:00 +0000
kMDItemContentModificationDate     = 2024-03-26 16:26:17 +0000
kMDItemContentType                 = "dyn.ah62d4rv4ge8043a"
kMDItemContentTypeTree             = (
    "public.item",
    "dyn.ah62d4rv4ge8043a",
    "public.data"
)
kMDItemDateAdded                   = 2024-03-26 16:25:51 +0000
kMDItemDisplayName                 = "Test notes.md"
kMDItemDocumentIdentifier          = 650720
kMDItemFSContentChangeDate         = 2024-03-26 16:26:17 +0000
kMDItemFSCreationDate              = 2024-03-26 16:25:51 +0000
kMDItemFSCreatorCode               = ""
kMDItemFSFinderFlags               = 0
kMDItemFSHasCustomIcon             = (null)
kMDItemFSInvisible                 = 0
kMDItemFSIsExtensionHidden         = 0
kMDItemFSIsStationery              = (null)
kMDItemFSLabel                     = 0
kMDItemFSName                      = "Test notes.md"
kMDItemFSNodeCount                 = (null)
kMDItemFSOwnerGroupID              = 20
kMDItemFSOwnerUserID               = 501
kMDItemFSSize                      = 15
kMDItemFSTypeCode                  = ""
kMDItemInterestingDate_Ranking     = 2024-03-26 00:00:00 +0000
kMDItemIsUploaded                  = 1
kMDItemIsUploading                 = 0
kMDItemKind                        = "Document"
kMDItemLastUsedDate                = 2024-03-26 16:28:30 +0000
kMDItemLastUsedDate_Ranking        = 2024-03-26 00:00:00 +0000
kMDItemLogicalSize                 = 15
kMDItemPhysicalSize                = 4096
kMDItemUseCount                    = 8
kMDItemUsedDates                   = (
    "2024-03-25 18:30:00 +0000"
)

-----------------------------------------------------------

Check file is in search scope...

✅ File exists within Alfred's default search scope

-----------------------------------------------------------

Check MDQuery file search...

✅ macOS returned a match for this file in your search scope.

File Search Results for search scope (
    "[0] /System/Volumes/Data/Users/zz/Library/CloudStorage/GoogleDrive-xxxxxxxxx@xxxxxx/My Drive/Alfred app/Alfred notes/Test notes.md"
)

File Search Results for ~/ (
    "[0] /System/Volumes/Data/Users/zz/Library/CloudStorage/GoogleDrive-xxxxxxxxx@xxxxxx/My Drive/Alfred app/Alfred notes/Test notes.md"
)

File Search Results for / (
    "[0] /System/Volumes/Data/Users/zz/Library/CloudStorage/GoogleDrive-xxxxxxxxx@xxxxxx/My Drive/Alfred app/Alfred notes/Test notes.md"
)

-----------------------------------------------------------

✅ Troubleshooting passed

⚠️ There were 1 warning(s)

**Comment by WinDroid00** [comment]
Thank you for your reply. I have replaced some personal info with xxxxxxxxx@xxxxxx. Sorry for that.

**Comment by vitorgalvao** [comment]
That means that as far as macOS is concerned, it doesn’t know what `.md` files are. Make sure you associate them with a proper app to open them, and if that doesn’t fix it, run steps 5 and 6 in the link above.

**Comment by WinDroid00** [comment]
Thank you Vitor! Your solution worked. [May I mention for noobs like me: that on Mac we need an app for md editor & md preview app (such as QLMarkdown, if your md editor does not have preview option) ]. Cheers once more. I will find ways to buy you a coffee one day.
