### ISSUE TITLE
Can't open any created notes

### ISSUE THREAD

**Issue by webstradev** [vitorgalvao/note-taker-workflow#2]
### Workflow version

v2024.3

### Alfred version

5.5[2257]

### macOS version

Sonoma 14.5

### Debugger output

```alfred_debugger
nothing because the command doesn't actually work
```

### More details

I have created some markdown notes, but they don't show up in nview. Txt notes show up just fine.

They show up normally in Alfred File serach

**Comment by vitorgalvao** [comment]
See https://github.com/vitorgalvao/note-taker-workflow/issues/1. Associate the markdown files with an app.

**Comment by webstradev** [comment]
> See #1. Associate the markdown files with an app.

Thanks for the quick reply. So I did look at #1 before opening this ticket and tried the steps described. My .md files were already associated with vscode and that still didn't solve it for me.

**Comment by webstradev** [comment]
Is the solution that I need to install a separate application for previewing?

**Comment by webstradev** [comment]
Okay so installing a plugin in vscode that enhances md previewing seems to have fixed the issue, however I had also installed QLMarkdown as mentioned in #1 . So if anyone else is running into this you can try either/both.

**Comment by vitorgalvao** [comment]
QLMarkdown is a Quick Look extension. In short, macOS needs to understand Markdown files are plain text (in the Context Type Tree) and that’s accomplished by associating them with an app that can open them.
